version: "3.8"

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: iheros
    volumes:
      - iheros-db-volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      backend-network:
        aliases:
          - db
  api:
    build:
      context: ./backend
    ports:
      - "3001:3001"
    depends_on:
      - db
    image: api:latest
    env_file:
      - ./backend/.env
    environment:
      DATABASE_URL: "postgres://postgres:postgres@db:5432/iheros"
      DATABASE_SSL: "false"
      TYPEORM_DRIVER_TYPE: "postgres"
    volumes:
      - ./backend/:/app/backend
    networks:
      backend-network:
        aliases:
          - api
      api-network:
        aliases:
          - api
    tty: "true"
  front:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - api
    env_file:
      - ./frontend/.env
    volumes:
      - ./frontend/:/app/frontend
      - /app/frontend/node_modules
    networks:
      - api-network
    tty: "true"
  migration:
    image: api:latest
    command: sh -c './wait-for.sh db:5432 -- npm run migration'
    environment:
      DATABASE_URL: "postgres://postgres:postgres@db:5432/iheros"
      DATABASE_SSL: "false"
      TYPEORM_DRIVER_TYPE: "postgres"
    depends_on:
      - db
    networks:
      - backend-network

volumes:
  iheros-db-volume:

networks:
  backend-network:
  api-network: